import psycopg2
con = psycopg2.connect(host = "localhost", user = "postgres", password = "akhil", port = 5432, dbname = "db2")
cur = con.cursor()
cur.execute ("create table users(name varchar(20), phone_number integer, DOB DATE, user_name varchar(20), password varchar(20))")
con.commit()
cur.execute("ALTER TABLE users ALTER COLUMN phone_number TYPE VARCHAR(15);")
con.commit()
cur.execute("create table statements(Date varchar(15), Particular varchar(20), Amount INT)")
con.commit()
cur.execute("ALTER TABLE statements ADD user_name varchar(20);")
con.commit()
cur.execute("ALTER TABLE statements ALTER COLUMN date TYPE DATE USING date::DATE;")
con.commit()
cur.close()
con.close()